Imports PriPROC6.Interface.oData
Imports System.Reflection

''' <summary>
'''
''' This code was generated by the Schema Utility.
'''
''' Form: ALINE_ONE as List(Of rowALINE_ONE)
''' Date: 13/05/2019
'''
''' </summary>
<oFormClass("rowALINE_ONE", "TRANSORDER_S")>
Public Class ALINE_ONE : Inherits oForm

    ''' <summary>
    ''' ALINE_ONE Constructor method.
    ''' </summary>
	''' <param name="Sender">The Assembly.GetExecutingAssembly of your project</param>
    ''' <param name="Parent">Optional: Parent oRow of this form</param>
    Sub New(byref Sender As Assembly, Optional Parent As oRow = Nothing)
        MyBase.New(Sender, Parent)

    End Sub

    ''' <summary>
    ''' Add a new row to the ALINE_ONE form.
    ''' </summary>
    ''' <returns>rowALINE_ONE</returns>
    Public Function AddRow() As rowALINE_ONE
        With Me
            .Add(New rowALINE_ONE(Me))
            Return .Last

        End With

    End Function

End Class

''' <summary>
''' Defines rows in the ALINE_ONE form.
''' </summary>
<oRowClass("ALINE_ONE", "serialALINE_ONE")>
Public Class rowALINE_ONE : Inherits oRow

    ''' <summary>
    ''' rowALINE_ONE Constructor method.
    ''' </summary>
    ''' <param name="Parent">Parent oForm of this row</param>
    Sub New(Parent As oForm)
        MyBase.New(Parent)

    End Sub
    
	''' <summary>
    ''' Get/set the TRANSORDER_S subform.
    ''' </summary>
    ''' <returns>TRANSORDER_S</returns>
	Public Property TRANSORDER_S As TRANSORDER_S
        Get
            Return MyBase.SubForms("TRANSORDER_S")
        End Get
        Set(value As TRANSORDER_S)
            MyBase.SubForms("TRANSORDER_S") = value
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Report No." Value of ALINE_ONE.
    ''' </summary>
    ''' <returns>Integer</returns>	
    <oDataColumn("Report No.", ReadOnly:=True)>
    Public Readonly Property DOC As Integer
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Date of Report" Value of ALINE_ONE.
    ''' </summary>
    ''' <returns>Date</returns>	
    <oDataColumn("Date of Report", mandatory:=True)>
    Public Property CURDATE As Date
        Get
            Return getProperty()
        End Get
        Set(value As Date)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Work Order" Value of ALINE_ONE.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Work Order", mandatory:=True, length:=22)>
    Public Property SERIALNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Work Order Quantity" Value of ALINE_ONE.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Work Order Quantity", ReadOnly:=True)>
    Public Readonly Property SERQUANT As Decimal
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Part Number" Value of ALINE_ONE.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Part Number", mandatory:=True, length:=15)>
    Public Property PARTNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Operation" Value of ALINE_ONE.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Operation", length:=16)>
    Public Property ACTNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Work Cell" Value of ALINE_ONE.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Work Cell", length:=6)>
    Public Property WORKCNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Employee ID" Value of ALINE_ONE.
    ''' </summary>
    ''' <returns>Integer</returns>	
    <oDataColumn("Employee ID")>
    Public Property USERID As Integer
        Get
            Return getProperty()
        End Get
        Set(value As Integer)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Employee Name" Value of ALINE_ONE.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Employee Name", ReadOnly:=True, length:=30)>
    Public Readonly Property BNAME As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Qty Completed" Value of ALINE_ONE.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Qty Completed")>
    Public Property QUANT As Decimal
        Get
            Return getProperty()
        End Get
        Set(value As Decimal)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Qty Rejected" Value of ALINE_ONE.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Qty Rejected")>
    Public Property SQUANT As Decimal
        Get
            Return getProperty()
        End Get
        Set(value As Decimal)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Defect Code" Value of ALINE_ONE.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Defect Code", length:=3)>
    Public Property DEFECTCODE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Descrip. of Defect" Value of ALINE_ONE.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Descrip. of Defect", ReadOnly:=True, length:=35)>
    Public Readonly Property DEFECTDESC As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Qty for MRB" Value of ALINE_ONE.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Qty for MRB")>
    Public Property MQUANT As Decimal
        Get
            Return getProperty()
        End Get
        Set(value As Decimal)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Factory Unit" Value of ALINE_ONE.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Factory Unit", ReadOnly:=True, length:=3)>
    Public Readonly Property UNITNAME As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Completed (Buy/Sell)" Value of ALINE_ONE.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Completed (Buy/Sell)")>
    Public Property TQUANT As Decimal
        Get
            Return getProperty()
        End Get
        Set(value As Decimal)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Rejected (Buy/Sell)" Value of ALINE_ONE.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Rejected (Buy/Sell)")>
    Public Property TSQUANT As Decimal
        Get
            Return getProperty()
        End Get
        Set(value As Decimal)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "MRB (Buy/Sell Units)" Value of ALINE_ONE.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("MRB (Buy/Sell Units)")>
    Public Property TMQUANT As Decimal
        Get
            Return getProperty()
        End Get
        Set(value As Decimal)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Buy/Sell Unit" Value of ALINE_ONE.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Buy/Sell Unit", ReadOnly:=True, length:=3)>
    Public Readonly Property TUNITNAME As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Packing Crates (No.)" Value of ALINE_ONE.
    ''' </summary>
    ''' <returns>Integer</returns>	
    <oDataColumn("Packing Crates (No.)")>
    Public Property NUMPACK As Integer
        Get
            Return getProperty()
        End Get
        Set(value As Integer)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Crate Type Code" Value of ALINE_ONE.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Crate Type Code", length:=8)>
    Public Property PACKCODE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Start Time" Value of ALINE_ONE.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Start Time", length:=5)>
    Public Property STIME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "End Time" Value of ALINE_ONE.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("End Time", length:=5)>
    Public Property ETIME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Span" Value of ALINE_ONE.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Span", length:=6)>
    Public Property ASPAN As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Start Labor" Value of ALINE_ONE.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Start Labor", length:=5)>
    Public Property EMPSTIME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "End Labor" Value of ALINE_ONE.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("End Labor", length:=5)>
    Public Property EMPETIME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Labor Span" Value of ALINE_ONE.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Labor Span", length:=6)>
    Public Property EMPASPAN As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Shift" Value of ALINE_ONE.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Shift", length:=8)>
    Public Property SHIFTNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Tool" Value of ALINE_ONE.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Tool", length:=15)>
    Public Property TOOLNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Rework?" Value of ALINE_ONE.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Rework?", length:=1)>
    Public Property RTYPEBOOL As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Set-up/Break (S/B)" Value of ALINE_ONE.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Set-up/Break (S/B)", length:=1)>
    Public Property MODE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "To Warehouse" Value of ALINE_ONE.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("To Warehouse", length:=4)>
    Public Property WARHSNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Bin" Value of ALINE_ONE.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Bin", length:=14)>
    Public Property LOCNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "New Pallet?" Value of ALINE_ONE.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("New Pallet?", length:=1)>
    Public Property NEWPALLET As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "To Pallet" Value of ALINE_ONE.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("To Pallet", length:=16)>
    Public Property TOPALLETNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Remove Oper. Number?" Value of ALINE_ONE.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Remove Oper. Number?", length:=1)>
    Public Property ACTCANCEL As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Remove Wk Order No.?" Value of ALINE_ONE.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Remove Wk Order No.?", length:=1)>
    Public Property SERCANCEL As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Work Order (ID)" Value of ALINE_ONE.
    ''' </summary>
    ''' <returns>Integer</returns>	
    <oDataColumn("Work Order (ID)")>
    Public Property SERIAL As Integer
        Get
            Return getProperty()
        End Get
        Set(value As Integer)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Part Revision No." Value of ALINE_ONE.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Part Revision No.", ReadOnly:=True, length:=10)>
    Public Readonly Property REVNAME As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get the Read Only "Max. No. Extensions" Value of ALINE_ONE.
    ''' </summary>
    ''' <returns>Integer</returns>	
    <oDataColumn("Max. No. Extensions", ReadOnly:=True)>
    Public Readonly Property VALIDITYEXTENSION As Integer
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get the Read Only "Acceptable" Value of ALINE_ONE.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Acceptable", ReadOnly:=True, length:=1)>
    Public Readonly Property ANALYSISVALID As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get the Read Only "Unacceptable" Value of ALINE_ONE.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Unacceptable", ReadOnly:=True, length:=1)>
    Public Readonly Property ANALYSISNOTVALID As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get the Read Only "Form Number" Value of ALINE_ONE.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Form Number", ReadOnly:=True, length:=16)>
    Public Readonly Property FORMNAME As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get the Read Only "Details" Value of ALINE_ONE.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Details", ReadOnly:=True, length:=24)>
    Public Readonly Property DETAILS As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get the Read Only "General Form" Value of ALINE_ONE.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("General Form", ReadOnly:=True, length:=1)>
    Public Readonly Property GENERAL As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Final" Value of ALINE_ONE.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Final", length:=1)>
    Public Property FINAL As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Form (ID)" Value of ALINE_ONE.
    ''' </summary>
    ''' <returns>Integer</returns>	
    <oDataColumn("Form (ID)", Key:=True)>
    Public Property FORM As Integer
        Get
            Return getProperty()
        End Get
        Set(value As Integer)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Key Line" Value of ALINE_ONE.
    ''' </summary>
    ''' <returns>Integer</returns>	
    <oDataColumn("Key Line", Key:=True)>
    Public Property KLINE As Integer
        Get
            Return getProperty()
        End Get
        Set(value As Integer)
            setProperty(value)
        End Set
    End Property


End Class

''' <summary>
''' A nullable version of rowALINE_ONE.
'''
''' This is used to deserialise JSON data
''' and should not be instantiated directly.
''' </summary>
Public Class serialALINE_ONE 

    Public Property DOC As Integer?
    Public Property CURDATE As Date?
    Public Property SERIALNAME As String
    Public Property SERQUANT As Decimal?
    Public Property PARTNAME As String
    Public Property ACTNAME As String
    Public Property WORKCNAME As String
    Public Property USERID As Integer?
    Public Property BNAME As String
    Public Property QUANT As Decimal?
    Public Property SQUANT As Decimal?
    Public Property DEFECTCODE As String
    Public Property DEFECTDESC As String
    Public Property MQUANT As Decimal?
    Public Property UNITNAME As String
    Public Property TQUANT As Decimal?
    Public Property TSQUANT As Decimal?
    Public Property TMQUANT As Decimal?
    Public Property TUNITNAME As String
    Public Property NUMPACK As Integer?
    Public Property PACKCODE As String
    Public Property STIME As String
    Public Property ETIME As String
    Public Property ASPAN As String
    Public Property EMPSTIME As String
    Public Property EMPETIME As String
    Public Property EMPASPAN As String
    Public Property SHIFTNAME As String
    Public Property TOOLNAME As String
    Public Property RTYPEBOOL As String
    Public Property MODE As String
    Public Property WARHSNAME As String
    Public Property LOCNAME As String
    Public Property NEWPALLET As String
    Public Property TOPALLETNAME As String
    Public Property ACTCANCEL As String
    Public Property SERCANCEL As String
    Public Property SERIAL As Integer?
    Public Property REVNAME As String
    Public Property VALIDITYEXTENSION As Integer?
    Public Property ANALYSISVALID As String
    Public Property ANALYSISNOTVALID As String
    Public Property FORMNAME As String
    Public Property DETAILS As String
    Public Property GENERAL As String
    Public Property FINAL As String
    Public Property FORM As Integer?
    Public Property KLINE As Integer?


End Class