Imports PriPROC6.Interface.oData
Imports System.Reflection

''' <summary>
'''
''' This code was generated by the Schema Utility.
'''
''' Form: TRANSORDER_S as List(Of rowTRANSORDER_S)
''' Date: 13/05/2019
'''
''' </summary>
<oFormClass("rowTRANSORDER_S")>
Public Class TRANSORDER_S : Inherits oForm

    ''' <summary>
    ''' TRANSORDER_S Constructor method.
    ''' </summary>
	''' <param name="Sender">The Assembly.GetExecutingAssembly of your project</param>
    ''' <param name="Parent">Optional: Parent oRow of this form</param>
    Sub New(byref Sender As Assembly, Optional Parent As oRow = Nothing)
        MyBase.New(Sender, Parent)

    End Sub

    ''' <summary>
    ''' Add a new row to the TRANSORDER_S form.
    ''' </summary>
    ''' <returns>rowTRANSORDER_S</returns>
    Public Function AddRow() As rowTRANSORDER_S
        With Me
            .Add(New rowTRANSORDER_S(Me))
            Return .Last

        End With

    End Function

End Class

''' <summary>
''' Defines rows in the TRANSORDER_S form.
''' </summary>
<oRowClass("TRANSORDER_S", "serialTRANSORDER_S")>
Public Class rowTRANSORDER_S : Inherits oRow

    ''' <summary>
    ''' rowTRANSORDER_S Constructor method.
    ''' </summary>
    ''' <param name="Parent">Parent oForm of this row</param>
    Sub New(Parent As oForm)
        MyBase.New(Parent)

    End Sub
    
	''' <summary>
    ''' Get / Set the "Part Number" Value of TRANSORDER_S.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Part Number", mandatory:=True, length:=15)>
    Public Property PARTNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Part Description" Value of TRANSORDER_S.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Part Description", ReadOnly:=True, length:=48)>
    Public Readonly Property PARTDES As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Work Order/Lot" Value of TRANSORDER_S.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Work Order/Lot", mandatory:=True, length:=22)>
    Public Property SERIALNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Part Revision No." Value of TRANSORDER_S.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Part Revision No.", length:=10)>
    Public Property REVNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "BOM Revision Number" Value of TRANSORDER_S.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("BOM Revision Number", ReadOnly:=True, length:=3)>
    Public Readonly Property REVNUM As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Status" Value of TRANSORDER_S.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Status", mandatory:=True, length:=16)>
    Public Property CUSTNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Serial Number" Value of TRANSORDER_S.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Serial Number", length:=20)>
    Public Property SERNUM As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Quantity" Value of TRANSORDER_S.
    ''' </summary>
    ''' <returns>Decimal</returns>	
    <oDataColumn("Quantity")>
    Public Property QUANT As Decimal
        Get
            Return getProperty()
        End Get
        Set(value As Decimal)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get the Read Only "Unit" Value of TRANSORDER_S.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Unit", ReadOnly:=True, length:=3)>
    Public Readonly Property UNITNAME As String
        Get
            Return getProperty()
        End Get

    End Property
    
	''' <summary>
    ''' Get / Set the "Operation/Pallet" Value of TRANSORDER_S.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Operation/Pallet", length:=16)>
    Public Property ACTNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Warehouse" Value of TRANSORDER_S.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Warehouse", mandatory:=True, length:=4)>
    Public Property WARHSNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Bin" Value of TRANSORDER_S.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Bin", mandatory:=True, length:=14)>
    Public Property LOCNAME As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Rework?" Value of TRANSORDER_S.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Rework?", length:=1)>
    Public Property REWORKFLAG As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Transaction (ID)" Value of TRANSORDER_S.
    ''' </summary>
    ''' <returns>Integer</returns>	
    <oDataColumn("Transaction (ID)")>
    Public Property TRANS As Integer
        Get
            Return getProperty()
        End Get
        Set(value As Integer)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Type" Value of TRANSORDER_S.
    ''' </summary>
    ''' <returns>String</returns>	
    <oDataColumn("Type", Key:=True, length:=1)>
    Public Property TYPE As String
        Get
            Return getProperty()
        End Get
        Set(value As String)
            setProperty(value)
        End Set
    End Property
    
	''' <summary>
    ''' Get / Set the "Key Line" Value of TRANSORDER_S.
    ''' </summary>
    ''' <returns>Integer</returns>	
    <oDataColumn("Key Line", Key:=True)>
    Public Property SNTKLINE As Integer
        Get
            Return getProperty()
        End Get
        Set(value As Integer)
            setProperty(value)
        End Set
    End Property


End Class

''' <summary>
''' A nullable version of rowTRANSORDER_S.
'''
''' This is used to deserialise JSON data
''' and should not be instantiated directly.
''' </summary>
Public Class serialTRANSORDER_S 

    Public Property PARTNAME As String
    Public Property PARTDES As String
    Public Property SERIALNAME As String
    Public Property REVNAME As String
    Public Property REVNUM As String
    Public Property CUSTNAME As String
    Public Property SERNUM As String
    Public Property QUANT As Decimal?
    Public Property UNITNAME As String
    Public Property ACTNAME As String
    Public Property WARHSNAME As String
    Public Property LOCNAME As String
    Public Property REWORKFLAG As String
    Public Property TRANS As Integer?
    Public Property TYPE As String
    Public Property SNTKLINE As Integer?


End Class